### ISSUE TITLE
Properly support time-series 3D data

### ISSUE THREAD

**Issue by martinp23** [stuart-cls/python-opusfc-dist#1]
Trying to open the 3D block from an Opus file, where opening 2D blocks in the same file works fine, I get the following error:

In [5]: dbs = opusFC.listContents(f)
print(dbs)
In [6]:
[('AB', '3D', 'NONE'), ('RIFG', '2D', 'NONE'), ('RSC', '2D', 'NONE'), ('SIFG', '3D', 'NONE'), ('SSC', '3D', 'NONE'), ('SPH', '3D', 'NONE'), ('TRC', '3D', 'NONE')]
## In [7]: data = opusFC.getOpusData(f, dbs[0])

KeyError                                  Traceback (most recent call last)
<ipython-input-7-e1ccd847504d> in <module>()
----> 1 data = opusFC.getOpusData(f, dbs[0])

opusFC.pyx in opusFC.getOpusData (opusFC.c:8202)()

KeyError: 'AOX'

[20160301.zip](https://github.com/stuart-cls/python-opusfc-dist/files/485707/20160301.zip)

**Comment by stuart-cls** [comment]
Thanks for the bug, and for including sample data. I can confirm this, it looks like we don't support time-series 3D data properly, as opposing to image/mapping data, AOX is the mapping origin parameter.

**Comment by stuart-cls** [comment]
This is now supported in `1.1.0`

**Comment by typorian** [comment]
Hi,
I'm using opusFC version 1.1.2 and I'm getting an error when trying the exact same thing. It looks like the output below. Is this expected? Should I maybe try to use 1.1.0?

`[('AB', '3D', 'NONE'), ('RIFG', '2D', 'NONE'), ('RSC', '2D', 'NONE'), ('SSC', '3D', 'NONE'), ('SPH', '3D', 'NONE'), ('SIFG', '3D', 'NONE'), ('TRC', '3D', 'NONE')]
Traceback (most recent call last):

  File "<ipython-input-10-250b53b646c5>", line 1, in <module>
    runfile('/opusfc_import.py', wdir='/python')

  File "/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/opusfc_import.py", line 14, in <module>
    data = opusFC.getOpusData(f,dbs[0])

  File "opusFC.pyx", line 1057, in opusFC.getOpusData

  File "opusFC.pyx", line 656, in opusFC.getOpusData.getANNOTable

  File "opusFC.pyx", line 603, in opusFC.getOpusData.getParams

ValueError: Unexpected value for reading parameter type: 10240`
