### ISSUE TITLE
Support dual-acquisition file type in listContents

### ISSUE THREAD

**Issue by andynave** [stuart-cls/python-opusfc-dist#10]
Hi,

I am working with dual-aquisition FTIR spectroscopy which generate OPUS file with two sets of spectrum, interferogram, ... see enclosed image.

![New Bitmap Image](https://user-images.githubusercontent.com/53347360/61964565-1871b000-afc6-11e9-8372-cdc26eb018df.jpeg)

opusFC.listContents do not list the entire content of this OPUS file, only listing one set of spectrum, interferogram, ...

Thank you.

**Comment by stuart-cls** [comment]
Thank you for your report. Could you please attach a small example file?

I may be able to fix this in the next release but I can't commit to a date for that at this time.

**Comment by andynave** [comment]
Hi Stuart,

Sorry, I already made my own software to read OPUS files.

Cheers,
Andy

**Comment by stuart-cls** [comment]
Glad you found a solution.

Closing as I don't have access to this file type.
