### ISSUE TITLE
Unknown annotation data type 1002

### ISSUE THREAD

**Issue by shober2** [stuart-cls/python-opusfc-dist#11]
When trying to load OPUS files that were written using an existing background (Bruker Lumos), I get the following error code when executing "opusFC.getOpusData(f, dbs[0])":

  File "opusFC.pyx", line 773, in opusFC.getOpusData

  File "opusFC.pyx", line 987, in opusFC.getOpusData

  File "opusFC.pyx", line 711, in opusFC.getOpusData.getANNOTable

ValueError: Unknown annotation data type 1002

So, I measured ATR spectra using an already existing background. 
This error does not occur when I load OPUS files where the background was measured specifically.

I attached a file so you can reproduce the error: 
[measurement_with_existing_background.zip](https://github.com/stuart-cls/python-opusfc-dist/files/5653341/measurement_with_existing_background.zip)

Would be really cool if this could be fixed. THX 

Paul

**Comment by stuart-cls** [comment]
Thanks for the detailed report and example file.

If you let me know your Python version and OS (for example Win64, Python 3.7) I can push a patch update to fix this.

**Comment by shober2** [comment]
Sure, I use Win64 with Python 3.8.3

Thanks a lot. 

Paul

**Comment by stuart-cls** [comment]
I've uploaded 1.2.2 to pypi for your platform. Feel free to re-open this issue if it's not fixed.

Thanks again!
