### ISSUE TITLE
Feature Request: Convert altered `DataReturn` object to an OPUS file.

### ISSUE THREAD

**Issue by JaiWillems** [stuart-cls/python-opusfc-dist#12]
I am working on a project with the FAR-IR Beamline at the CLS to remove interference fringes from FTIR spectrographs.

Currently, I am using `OPUSFC` to import OPUS file data into an `OPUSData` class from an `OPUSLoader` function as seen [here](https://github.com/JaiWillems/Interference-Fringe-Removal/blob/main/IFR/spectra/dataobjects.py). It would be ideal to be able to convert the spectrographs with removed fringes back into an OPUS file such that users can open the evolved data in a natural software.

Ideally, this could be accomplished by converting a `DataReturn` object back into an OPUS file to get the following workflow:

```Python
data_blocks = opusFC.listContents(path)

for data_block in data_blocks:
    opusFC.getOpusData(path, data_block).x = ...  # Complete an operation on x.
    opusFC.getOpusData(path, data_block).y = ...  # Complete an operation on y.

opusFC.putOpusData(path)  # Save altered `DataReturn` object to an OPUS file.
```

**Comment by typorian** [comment]
This would be absolutely great, as OPUS is lacking in features and comfort, and a lot of the automation is not easy to use.

**Comment by stuart-cls** [comment]
@typorian Apologies, I replied privately to Jai and forgot to update this issue.

We provide this library to enable our users to bring their data _in_ to our supported data analysis software, [Quasar](https://quasar.codes/). I’m afraid we can’t accommodate this feature. One of the primary motivations of the software development we do at the beamline is to help users have access to and analyze their data in open, reproducible software and formats. Storing processed data in proprietary, undocumented formats just isn’t on the roadmap.

In addition, philosophical concerns aside, we don’t have sufficient information about the format to write a file that we could be confident using with various software. A very large amount of work would be required to develop this feature and fully test it.

**Comment by typorian** [comment]
@stuart-cls No worries, I didn't actually expect this to happen. I'm absolutely with you on your philosophical sentiment, I'm just feeling the pain of philosophy conflicting with reality.
