### ISSUE TITLE
orange 3.31 install of opusFC addon

### ISSUE THREAD

**Issue by jbeattie55** [stuart-cls/python-opusfc-dist#14]
Addon failes to install OpusFC addon.  following error appears:
 ERROR: Could not find a version that satisfies the requirement opusFC==1.2.6 (from versions: 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0a3)
ERROR: No matching distribution found for opusFC==1.2.6

**Comment by stuart-cls** [comment]
Thanks, I released 1.2.6 as a python 3.10 only release. It has no code changes from 1.2.5

I am working on a 1.3.0 release which will support all, the normal pythons/platforms.

For now I suggest installing version 1.2.5 with `pip install opusfc==1.2.5`. For Orange you can do this from the *Orange Command Prompt*. Alternatively, the Quasar distribution comes with opusFC built-in: https://quasar.codes/download

**Comment by stuart-cls** [comment]
I have released version 1.3.0 with full python version support, so this issue should be solved. Please re-open if that is not the case.
