### ISSUE TITLE
opusFC.isOpusFile() on empty files

### ISSUE THREAD

**Issue by zacmiki** [stuart-cls/python-opusfc-dist#15]
Good morning, 
first of all thanks for the splendid work with the OpusFC module and Quasar things. 
I work with pretty big directories of OPUS files and I need to scan for the OPUS files to then process them and I encountered a problem with `opusFC.isOpusFile(file)` 
The fact is that it seems it gives an

`error: unpack requires a buffer of 4 bytes`

when the method encounters an empty file (zero bytes file). Most of the times this is not a problem but sometimes it happens that OPUS ends up Saving a "null" file

Of course this can be worked around but maybe you might like to fix it. 
In my case I did need to create a list of all (and only) the OPUS files in all dirs and subdirs and so I did it by skipping the empty files like like in the procedures below

Have a good day and once again congrats on the wonderful work 
**(IR Forever ! )**

- - - Code Below - - -

def allOpusFiles(dirName):
    '''Returns a list with all the OPUS files in that dir and all subdirs'''
    import os
    import opusFC

    # Get a list of all files in the specified directory and its subdirectories
    all_files = getListOfFiles(dirName)

    # Use a list comprehension to create a list of the names of the non-empty Opus files
    opus_files = [file for file in all_files if os.path.getsize(file) > 0 and opusFC.isOpusFile(file)]

    return opus_files

#------------------------------------------

def getListOfFiles(dirName):
    import os

    # Create an empty list to store the names of the files
    fileList = []

    # Use the os.walk function to iterate over the files and directories in the specified directory
    for root, dirs, files in os.walk(dirName):
        # Add the names of the files in the current directory to the file list
        for file in files:
            fileList.append(os.path.join(root, file))

    return fileList

#------------------------------------------`

**Comment by stuart-cls** [comment]
Thank you for the report and kind feedback! I will try to fix this for the next release.
Best,
Stuart

**Comment by stuart-cls** [comment]
This should be fixed in 1.4.0, thanks again.
