### ISSUE TITLE
Extract microscope (visible) image

### ISSUE THREAD

**Issue by cmft** [stuart-cls/python-opusfc-dist#3]
Hi,
Is it possible to get the microscope image from the opus file? 
With `opusFC.listContents(f)` I only see the spectra contents (AB, RSC,TRC, and SSC).

Many thanks in advance.

**Comment by stuart-cls** [comment]
Hi, 
Unfortunately at the moment this is not implemented. It's on our radar but I don't know when I'll have time to work on it.

**Comment by cmft** [comment]
Ok. 
Thank you very much for your quick answer

**Comment by stuart-cls** [comment]
I'm re-opening this, as it is an outstanding request.

**Comment by stuart-cls** [comment]
This has now been implemented in `1.2.0`. See https://stuart-cls.github.io/python-opusfc-dist/ for documentation of the new interface.
