### ISSUE TITLE
Remove numpy as a dependency?

### ISSUE THREAD

**Issue by markotoplak** [stuart-cls/python-opusfc-dist#4]
One of orange-infrared users can not install the infrared add-on due to the numpy version mismatch:

```
Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 22:58:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import orangecontrib.infrared.data
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
```

Because you can not distribute compiled packages for different numpy versions through PyPi I propose not using numpy altogether. I instead propose using array.array. It is fast, memory efficient, and comes with python so there should be no package dependency conflicts. It is sufficient for file reading while the end user, who wants to somehow manipulate data, can easily convert them to numpy.

This is my current approach for another proprietary reader. What do you think?

**Comment by markotoplak** [comment]
I know this would break interface compatibility but I do not see any other way to guarantee flexibility with different python installation. Would love to hear of another solution, though.

**Comment by markotoplak** [comment]
BTW, this is not a problem of opusFC as it is not even imported in that stage, but is just something we could run into eventually.

**Comment by stuart-cls** [comment]
I waited long enough that numpy fixed this: now numpy has a backwards-compatible C API :) https://numpy.org/devdocs/dev/depending_on_numpy.html#build-time-dependency
