### ISSUE TITLE
Binary for 32-bit Python 3.5 on Windows

### ISSUE THREAD

**Issue by markotoplak** [stuart-cls/python-opusfc-dist#5]
An Orange Infrared user on 32-bit Anaconda with Python 3.5 (he needs it that way for compatibility with other libraries) contacted me that his install failed due to missing opusFC binary.

Is it possible that this binary is created? I think it is the only Windows binary missing from https://pypi.python.org/pypi/opusFC/1.1.0

**Comment by stuart-cls** [comment]
Sure thing! I'm running a 32-bit on 3.6 for a specific application but I missed that anyone would need 3.5 specifically.

I'll update this when it's ready.

**Comment by stuart-cls** [comment]
I've uploaded `opusFC-1.1.0-cp35-cp35m-win32`

Turns out there was actually a problem with numpy 1.11 on Anaconda python 3.5 / win32, which is why I hadn't uploaded it before. If updated to 1.13 it works fine. Another reason to do #4 I guess!
