### ISSUE TITLE
How to read time related to the data?

### ISSUE THREAD

**Issue by pradeepchandra551** [stuart-cls/python-opusfc-dist#6]
I have a opus file. When i opened it in vim I can notice that there are several time stamps in the data. How to get time values from the file using opusFC.

**Comment by stuart-cls** [comment]
For most files, you can use the SRT parameter in the parameters dictionary (`data.parameters['SRT']`) which returns a unix timestamp, either in local or UTC time depending on the computer the file was acquired on.

For more complex files like MultiRegion or 3D TimeResolved, see http://pythonhosted.org/opusFC/

Finally, you can also see how we use opusFC in Orange by looking at the [orange-spectroscopy.data.OPUSReader](https://github.com/markotoplak/orange-infrared/blob/master/orangecontrib/spectroscopy/data.py#L386) class.

Hope that helps!

**Comment by pradeepchandra551** [comment]
Thank you Stuart. I got the time by using data.parameters['SRT'].
