### ISSUE TITLE
Only binary wheels of opusFC can be provided

### ISSUE THREAD

**Issue by stuart-cls** [stuart-cls/python-opusfc-dist#7]
Ref https://github.com/Quasars/orange-spectroscopy/issues/190#issue

@yurivict Can you please provide more details here?

**Comment by yurivict** [comment]
There is no source tarball among the supplied files in https://pypi.org/project/opusFC/#files
The FreeBSD port infrastructure can't build the package.

**Comment by stuart-cls** [comment]
As I think has probably become clear in https://github.com/Quasars/orange-spectroscopy/issues/190 , for legal reasons we can only support platforms that are targeted by the python wheel project: Windows, MacOS, manylinux. This is clearly documented in the project documentation at https://pythonhosted.org/opusFC

I am sympathetic to your situation but as there is no solution to this problem at this time, I am going to close this issue wontfix.
