### ISSUE TITLE
Unhandled parameter type 10240

### ISSUE THREAD

**Issue by stuart-cls** [stuart-cls/python-opusfc-dist#8]
_Originally posted by @typorian in https://github.com/stuart-cls/python-opusfc-dist/issues/1#issuecomment-456848654_

Hi,
I'm using opusFC version 1.1.2 and I'm getting an error when trying the exact same thing. It looks like the output below. Is this expected? Should I maybe try to use 1.1.0?

`[('AB', '3D', 'NONE'), ('RIFG', '2D', 'NONE'), ('RSC', '2D', 'NONE'), ('SSC', '3D', 'NONE'), ('SPH', '3D', 'NONE'), ('SIFG', '3D', 'NONE'), ('TRC', '3D', 'NONE')]
Traceback (most recent call last):

  File "<ipython-input-10-250b53b646c5>", line 1, in <module>
    runfile('/opusfc_import.py', wdir='/python')

  File "/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/opusfc_import.py", line 14, in <module>
    data = opusFC.getOpusData(f,dbs[0])

  File "opusFC.pyx", line 1057, in opusFC.getOpusData

  File "opusFC.pyx", line 656, in opusFC.getOpusData.getANNOTable

  File "opusFC.pyx", line 603, in opusFC.getOpusData.getParams

ValueError: Unexpected value for reading parameter type: 10240`

_Originally posted by @typorian in https://github.com/stuart-cls/python-opusfc-dist/issues/1#issuecomment-456848654_

**Comment by stuart-cls** [comment]
Hi @typorian,

Thanks for your report. This is issue is not specific to time-resolved data sets. 

If the failing datafile is not large, can you email it to me? Either way I should be able to fix this bug, although I can't commit to a timeline right now.

Best,
Stuart

**Comment by typorian** [comment]
@stuart-cls 
I attached a little example file. Do you need any more information on this? It was created in OPUS 7.2 by using the chromatography mode. I have many files that were created in this way and the error occurs regardless of their size so I think it is fine as an example.
Thank you for looking into it.

[example_unhandled_parameter_type_10240_opusFC.zip](https://github.com/stuart-cls/python-opusfc-dist/files/2790687/example_unhandled_parameter_type_10240_opusFC.zip)

**Comment by stuart-cls** [comment]
This has been fixed in `1.2.0`.
